name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 1.2.1+5

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.1
  audioplayers: ^0.17.0
  circular_countdown_timer: ^0.0.8
  confetti: ^0.5.4+1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
