name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 4.0.0+400

environment:
  sdk: 3.6.1

dependencies:
  flutter:
    sdk: flutter

  #
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  #

  app_settings: 5.1.1 # Used to check and update microphone permission
  audio_waveforms: 1.2.0 # Generate waveforms while recording audio and when listening to audio files
  circular_countdown_timer: 0.2.4 # Used for showing the timer
  easy_localization: 3.0.7 # Localization
  flutter_staggered_animations: 1.1.1 # Used for animating widgets
  flutter_svg: 2.0.17 # SVG rendering library
  get_it: 8.0.3 # Dependency injection
  hive_ce: 2.9.0 # Used for persistent storage
  hive_ce_flutter: 2.2.0 # Easier integration of Hive with Flutter
  intl: 0.20.1 # Used for date formatting
  just_audio: 0.9.43 # Used to play audio files
  logger: 2.5.0 # Used for console logging
  package_info_plus: 8.1.3 # Used to get the app version
  path_provider: 2.1.5 # For finding commonly used locations on the filesystem
  rive: 0.13.20 # Renders Rive animations in Flutter
  timeago: 3.7.0 # To show when were games played
  url_launcher: 6.3.1 # Used to launch URLs in native browser
  video_player: 2.9.2 # Used to play videos
  wakelock_plus: 1.2.10 # Used for keeping the screen active while game is running
  watch_it: 1.6.2 # State management

dev_dependencies:
  build_runner: 2.4.14 # Used for code generation
  flutter_launcher_icons: 0.14.2 # Used to generate app icons
  flutter_native_splash: 2.4.4 # Used to generate splash screen
  hive_ce_generator: 1.8.2 # Generates Hive adapters

dependency_overrides:
  intl: 0.20.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/videos/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-SemiBold.ttf
          weight: 600
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700

# Run Hive code generation with `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#152544'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#152544'
    theme_color: '#152544'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash.png'
  android_12:
    color: '#152544'
    color_dark: '#152544'
