name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  url_launcher: ^5.5.0
  circular_countdown_timer: ^0.0.4
  audioplayers: ^0.15.1
  confetti: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon_adaptive.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts\Sen\Sen-Regular.ttf
        - asset: fonts\Sen\Sen-Bold.ttf
          weight: 700
