name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 2.7.5+19

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # 
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  # 

  circular_countdown_timer: 0.2.3 # Used for showing the timer
  flutter_screenutil: 5.7.0 # Used for adapting screen and font size
  flutter_staggered_animations: 1.1.1 # Used for animating widgets
  flutter_svg: 2.0.4 # SVG rendering library
  get: 4.6.5 # State management, dependency injection, etc.
  hive: 2.2.3 # Used to store data for Stats
  hive_flutter: 1.1.0 # Easier integration of Hive with Flutter
  intl: 0.18.0 # Used for date formatting
  just_audio: 0.9.32 # Used to play audio files
  logger: 1.3.0 # Small, easy to use and extensible logger which prints beautiful logs
  rive: 0.10.3 # Renders Rive animations in Flutter
  package_info_plus: 3.0.3 # To get the app version and show on the relevant screen
  timeago: 3.4.0 # To show when were last games played
  url_launcher: 6.1.10 # Used to launch URLs in native browser

dev_dependencies:
  build_runner: 2.3.3 # Used for code generation
  flutter_launcher_icons: 0.12.0 # Used to generate app icons
  flutter_native_splash: 2.2.19 # Used to generate splash screen
  hive_generator: 2.0.0 # Generates Hive adapters

  # Run Hive code generation
  # flutter packages pub run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#182F3F'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
