name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 1.2.2+6

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  circular_countdown_timer: ^0.2.0
  confetti: ^0.6.0
  cupertino_icons: ^1.0.4
  flutter_screenutil: ^5.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  url_launcher: ^6.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon.png'

flutter_native_splash:
  android: true
  ios: true
  color: '#182F3F'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
