name: modernialias
description: Ovo je moja Alias aplikacija.
publish_to: 'none'
version: 4.5.0+450

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter

  #
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  #

  app_settings: 6.1.1 # Used to check and update microphone permission
  audio_waveforms: 1.3.0 # Generate waveforms while recording audio and when listening to audio files
  circular_countdown_timer: 0.2.4 # Used for showing the timer
  easy_localization: 3.0.7+1 # Localization
  flutter_staggered_animations: 1.1.1 # Used for animating widgets
  flutter_svg: 2.2.0 # SVG rendering library
  get_it: 8.0.3 # Dependency injection
  hive_ce: 2.11.3 # Used for persistent storage
  hive_ce_flutter: 2.3.1 # Easier integration of Hive with Flutter
  intl: 0.20.2 # Used for date formatting
  just_audio: 0.10.4 # Used to play audio files
  logger: 2.6.0 # Used for console logging
  package_info_plus: 8.3.0 # Used to get the app version
  path_provider: 2.1.5 # For finding commonly used locations on the filesystem
  rive: 0.13.20 # Renders Rive animations in Flutter
  share_plus: 11.0.0 # Used for sharing played games
  timeago: 3.7.1 # To show when were games played
  url_launcher: 6.3.1 # Used to launch URLs in native browser
  video_player: 2.10.0 # Used to play videos
  wakelock_plus: 1.3.2 # Used for keeping the screen active while game is running
  watch_it: 1.6.5 # State management

dev_dependencies:
  build_runner: 2.5.4 # Used for code generation
  flutter_launcher_icons: 0.14.4 # Used to generate app icons
  flutter_native_splash: 2.4.6 # Used to generate splash screen
  hive_ce_generator: 1.9.2 # Generates Hive adapters

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/videos/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-SemiBold.ttf
          weight: 600
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700

# Run Hive code generation with `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#1C3D5F'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#1C3D5F'
    theme_color: '#1C3D5F'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash.png'
  android_12:
    color: '#1C3D5F'
    color_dark: '#1C3D5F'
