name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 2.9.5+23

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  #

  audio_waveforms: 1.0.4 # Generate waveforms while recording audio or from audio files
  circular_countdown_timer: 0.2.3 # Used for showing the timer
  easy_localization: 3.0.2 # Localization
  flutter_staggered_animations: 1.1.1 # Used for animating widgets
  flutter_riverpod: 2.3.6 # State management, dependency injection, etc.
  flutter_svg: 2.0.6 # SVG rendering library
  hive: 2.2.3 # Used to store data for Stats
  hive_flutter: 1.1.0 # Easier integration of Hive with Flutter
  intl: 0.18.1 # Used for date formatting
  just_audio: 0.9.34 # Used to play audio files
  logger: 1.4.0 # Small, easy to use and extensible logger which prints beautiful logs
  package_info_plus: 4.0.2 # To get the app version and show on the relevant screen
  path_provider: 2.0.15 # For finding commonly used locations on the filesystem
  rive: 0.11.2 # Renders Rive animations in Flutter
  timeago: 3.4.0 # To show when were last games played
  url_launcher: 6.1.11 # Used to launch URLs in native browser
  video_player: 2.7.0 # Used to play videos

dev_dependencies:
  build_runner: 2.4.5 # Used for code generation
  flutter_launcher_icons: 0.13.1 # Used to generate app icons
  flutter_native_splash: 2.3.1 # Used to generate splash screen
  hive_generator: 2.0.0 # Generates Hive adapters

  # Run Hive code generation with `dart run build_runner build -d`

dependency_overrides:
  intl: 0.18.1 # Because of easy_localization: 3.0.2

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  background_image: 'assets/splash.png'
  android_12:
    color: '#182F3F'


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/videos/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
