name: modernialias
description: Ovo je moja Alias aplikacija.

publish_to: 'none'

version: 2.2.0+16

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # ------------------------------------
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  # ------------------------------------

  circular_countdown_timer: ^0.2.2 # Used for showing the timer
  flutter_screenutil: ^5.5.3+2 # Used for adapting screen and font size
  flutter_staggered_animations: ^1.0.0 # Used for animating widgets
  flutter_svg: ^1.1.1+1 # SVG rendering library
  get: ^4.6.5 # State management, dependency injection, etc.
  hive: ^2.2.3 # Used to store data for Stats
  hive_flutter: ^1.1.0 # Easier integration of Hive with Flutter
  just_audio: ^0.9.27 # Used to play audio files
  logger: ^1.1.0 # Small, easy to use and extensible logger which prints beautiful logs
  lottie: ^1.3.0 # Renders Lottie animations in Flutter
  package_info_plus: ^1.4.2 # To get the app version and show on the relevant screen
  url_launcher: ^6.1.4 # Used to launch URLs in native browser

dev_dependencies:
  build_runner: ^2.1.11 # Used for code generation
  flutter_launcher_icons: ^0.9.3 # Used to generate app icons
  flutter_native_splash: ^2.2.3+1 # Used to generate splash screen
  hive_generator: ^1.1.3 # Generates Hive adapters

  # Run Hive code generation
  # flutter packages pub run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#182F3F'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#182F3F'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
