// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:modernialias/constants/enums.dart';
import 'package:modernialias/models/normal_game_stats/normal_game_stats.dart';
import 'package:modernialias/models/played_word/played_word.dart';
import 'package:modernialias/models/quick_game_stats/quick_game_stats.dart';
import 'package:modernialias/models/round/round.dart';
import 'package:modernialias/models/settings/settings.dart';
import 'package:modernialias/models/team/team.dart';
import 'package:modernialias/models/time_game_stats/time_game_stats.dart';
import 'package:modernialias/models/used_words/used_words.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnswerAdapter());
    registerAdapter(FlagAdapter());
    registerAdapter(NormalGameStatsAdapter());
    registerAdapter(PlayedWordAdapter());
    registerAdapter(QuickGameStatsAdapter());
    registerAdapter(RoundAdapter());
    registerAdapter(SettingsHiveAdapter());
    registerAdapter(TeamAdapter());
    registerAdapter(TimeGameStatsAdapter());
    registerAdapter(UsedWordsAdapter());
  }
}
