update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy a new release to the App Store"
  lane :release do
    # Build app
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    # Upload to App Store
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: true,
      app_version: "4.1.3",
      build_number: "413"
      )

      # Show notification
      notification(subtitle: "Success", message: "New release deployed on the App Store")
  end
end
