# Check for `Fastlane` updates
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build & deploy a new release to the Google Play"
  lane :release do
    # Build Flutter app
    sh("puro flutter clean")
    sh("puro flutter pub get")
    sh("puro flutter build appbundle")

    # Upload to Play Store
    supply(
      json_key: "/Users/josipkilic/Documents/fastlane-451713-01bb44a559be.json",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      )

    # Show notification
    notification(
      content_image: "/Users/josipkilic/Projects/moderni_alias/assets/icon.png",
      title: "Moderni Alias",
      subtitle: "Success",
      message: "New release deployed to the Play Store",
      )
  end
end
