update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new release to the Google Play"
  lane :release do
    # Build app
    gradle(task: "clean assembleRelease")

    # Upload to Play Store
    supply(
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      track: "production",
      json_key: "/Users/josipkilic/Documents/modernialias-b66055dd2c28.json",
      version_name: "4.1.3",
      version_code: "413"
      )

    # Show notification
    notification(subtitle: "Success", message: "New release deployed on the Play Store")
  end
end
